### ISSUE TITLE
Not really an issue but yet, a thank you

### ISSUE THREAD

**Issue by Mikast2339** [AgentMC/Sao20#2]
Well, first of all, I want to say thank you for translating the vol 19 and vol 20 of Light-Novel "Sword Art Online". I just started to read the series recently, but no where to find the translation for the "Moon Cradle". Luckily enough to find on this page. 
I'm happy that I can read this two volumes in English (though I should have bought the Japanese to read even though my stats of Japanese is not good, maybe I should buy one in the future to support the author). So one again, thank you for translating it.

Your translation is really easy to read even you used the programs to translate, but there may just one thing I want to say, it's about "yujio", I understand the katakana when translated to romaji is "Yujio", I'm not complain or anything, you can write it's as "Eugeo" if you consider. Thank you

**Comment by AgentMC** [comment]
Hello, thank you for reading the Moon Cradle in my translation. I'm glad you find it easy to read, though I know it's far from perfect.

Regarding the name - this is one of the names I changed in these translations deliberately compared to some other translators. The reason for this is that names in Underworld are not coming from any real name in Real World. As we know from the volume 16 and 17 (if I remember correctly), each syllable in name represents a certain element of personality the parents wish for their child to gain. It just happens so that Yujio's parents wished for something close by pronunciation to western name of Eugene.  In fact it's two completely unrelated names and using Eugeo, in my opinion, is simply incorrect interpretation of romaji. 

I think until a certain moment, Kawahara-san really wanted Underworld names mimic the Western names or words - there you have Eugeo, Fanatio, Wolo (war), Solterina (sort line? :) ), Quinella (queen) etc. But then he came up with this concept of syllable-based character tweaking and that's what we have in final version with Bercouli, Renri, Rirupirin, Isukan (Iskhan - no really, I don't know why this form of his name is in wiki, he's not of middle-South-Asian type) etc.

**Comment by Mikast2339** [comment]
So that's why, I understand now. Thank you for your answer
